### ISSUE TITLE
Example config is not complete

### ISSUE THREAD

**Issue by cbialorucki** [BenWirus/ZombieVoters#1]
Without a "page_cooldown_sec" variable in the configuration file, this code will not work. I will add one to the example config.

**Comment by epictimesforall** [comment]
Come Join Us. 
https://thedonald.win/p/11PpKYnF2Y/to-programmers-out-there-someone/

**Comment by BenWirus** [comment]
@epictimesforall I replied in that thread, thanks for reaching out.
