### ISSUE TITLE
Cool stuff.  Can you confirm you have to be subscribed to Ancestry?

### ISSUE THREAD

**Issue by myceliumcr** [BenWirus/ZombieVoters#2]
I tried it and even with the Ancestry free account can't get far.
I think I need to subscribe.   right?
What if any limitation have you run into with scraping them?
Lots of data to scrape. Would be cool if several people can split up the scrapes to gather one larger data set  :)

**Comment by BenWirus** [comment]
Correct, right now it requires an Ancestry subscription. Something that would improve the accessibility of this script would be finding a free of charge source for the Social Security Death Index. Generally the info required is first & last name, zip code, date of birth, and date of death.

**Comment by BenWirus** [comment]
I just found out from someone in #3 that  you can start a 14 day trial on Ancestry.
