### ISSUE TITLE
Death Index Worker Nodes Needed

### ISSUE THREAD

**Issue by BenWirus** [BenWirus/ZombieVoters#3]
If you or anyone you know has an ancestry.com subscription, consider volunteering your computing power to downloading the Social Security Death Index. I'm able to run around 4-5 instances of the script, each working on a different year, before I get a captcha. Please reply here if we have volunteers so we can organize the effort.

**Comment by Jambre** [comment]
I have a 14 day trial right now, willing to purchase a subscription. Just started looking at the code

**Comment by Jambre** [comment]
I also retrieved PA's voter list export, all the data there looks real ~~however the DOBs for each voter is scrambled.~~

I have no clue what I did yesterday to make the list work differently today. The DOBs are matching. I spent hours trying to figure out why there was an issue. Today it is matching... so I'll work on pulling PA's Death Index and start cross referencing it.

**Comment by AlexMusabelliu** [comment]
> I also retrieved PA's voter list export, all the data there looks real ~however the DOBs for each voter is scrambled.~
> 
> I have no clue what I did yesterday to make the list work differently today. The DOBs are matching. I spent hours trying to figure out why there was an issue. Today it is matching... so I'll work on pulling PA's Death Index and start cross referencing it.

I opened PA data too and excel for some reason shows some of the dates as a series of # when it firsts loads the file. If you click on the cell and click off, however, it'll fix the issue for all the dates matching itself. The data is probably fine, but excel has a hard time converting it to a date (which it is known to have issues with).

**Comment by BenWirus** [comment]
> Today it is matching... so I'll work on pulling PA's Death Index and start cross referencing it.

You might want to pull my latest commit, I fixed a bug where it would crash when there was no zip code in the ancestry data.

**Comment by Jambre** [comment]
I'm having a tough time getting this to function properly. Could I get some help via Discord? Jamber#2699

**Comment by BenWirus** [comment]
I'm not sure how to connect with people on Discord. Would you mind posting your issue here as a new issue so other can get help from the resolution if they have the same issue?

**Comment by Jambre** [comment]
I actually think it's a deeper problem with my Python installation. If not I'll let you know.

**Comment by BenWirus** [comment]
Just a heads up, I've only tested this on Windows and MacOS. I installed Python 3.9 on Windows with [Chocolatey](https://chocolatey.org/) and Python 3.9 on MacOS using [Home Brew](https://brew.sh/).

**Comment by Technetium1** [comment]
@BenWirus depending on the captcha service used that shouldn't be too hard to get around...

**Comment by BenWirus** [comment]
@Technetium1 It's recaptcha not sure if it's v2 or v3. I have no experience getting around them. I updated the script to sleep and then reload the page once and see if it goes away, and it does most of the time, if it's still there the script waits for you to resolve the captcha. If you know of a better way to deal with them please let me know.

**Comment by Technetium1** [comment]
Try to bypass it before you pay to solve https://github.com/teal33t/captcha_bypass

**Comment by astral1911** [comment]
I have a paid Ancestry account, got this working and been pulling deaths/zombies for MI Wayne county for a couple of days. How can we combine results?

**Comment by BenWirus** [comment]
I'm going to close this as I'm almost done with Wayne County. If you are still using ancestry please update the master branch and follow the new instructions in the readme, you'll need to start fresh.
